### PR TITLE
fix #44 return.df option for icd9Charlson

### LINKED ISSUE #44: icd9Charlson with return.df=TRUE yields error in data.frame(): arguments imply differing number of rows
Using RStudio Version 0.98.1091, R version 3.1.2 (2014-10-31) on Windows 7 x64

Tried every combination of Character v. Factor for input data.frame columns and stringsAsFactors being true or false, but always get the same result
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 197, 11

In this case, 197 is my total number of ICD-9 codes and 11 is the number of distinct visits.

Easy to workaround by using return.df=FALSE and merging manually.

Thanks for this very useful package

### PR DESCRIPTION
**Pull request by wmurphyrd**
For the return.df issue #44 : 
The problem stemmed from building the return data frame using the source data visitId column that is in long format with duplicates of visitId. This lead to the mismatch of row count with the one-per-visitId result of icd9CharlsonComorbid.

Rather than recalculate the unique visitIds when building the data frame, I rearrange a little to preserve that part of the result from icd9ComorbidQuanDeyo.

For the calculation issue #46 :
I went with the double transpose method rather than the sweep() function because it is supposedly faster for large data sets. The results now match what I get from doing manual calculations of the Charlson index on my data.

### CODE REVIEW

**Comment by jackwasey** [comment]
That's great - thanks for spotting the problem and offering a patch. I'll take a look at it tomorrow, but looks good at first sight.

**Comment by jackwasey** [comment]
Thanks again for the patches. Do you think you could add tests cases you used to identify the original problem?

**Comment by wmurphyrd** [comment]
I can't share the original data due to our IRB, but here's a test case that will trigger #44
```> mydf <- data.frame(visitId = c("a", "b", "c","a","b","d"),
+                    icd9 = c("441", "412.93", "044.9","250.0","250.0","250.0"),
+                    stringsAsFactors = TRUE)
> icd9Charlson(mydf,return.df=TRUE)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 6, 4```

I'll work on creating an example for #46 as well, if you need it

**Comment by wmurphyrd** [comment]
This will demonstrate #46 
```
mydf<-data.frame(visitId="a",icd9="250.0")
comorbids<-icd9ComorbidQuanDeyo(mydf,isShort=FALSE)
set.seed(123)
# Fill a QuanDeyo comorbidity data frame with random data
comorbids<-rbind(comorbids,data.frame(visitId=letters[2:10],
                                      matrix(runif((ncol(comorbids)-1)*9)>0.7,ncol=17,
                                             dimnames=list(character(0),names(comorbids[2:18])))))
print(comorbids[2,]) # Case 2: Dementia, LiverMild, Cancer, HIV
c2.inv <-cbind(t(comorbids[2,2:18]),c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 6, 6))
print(c2.inv) # Show scores for each comorbditiy for Case 2
print(sum(apply(c2.inv,1,prod))) # Charlson score for Case 2 is 10
print(icd9CharlsonComorbid(comorbids,applyHierarchy=TRUE)[2]) # Returns score of 6 for Case 2
```

**Comment by wmurphyrd** [comment]
I'm new to this, so let me know if you need anything else. I also wanted to know if you're interested in adding other scoring systems. I created methods to get a [van Walraven score for Quan-Elixhauser comorbidities] (http://www.ncbi.nlm.nih.gov/pubmed/?term=19433995) based on your methods for the Charlson score.

**Comment by jackwasey** [comment]
Other scoring systems would be great. I'll be happy to put together your patch and test. Have a lot going on right now, so it may be a few days before I get to making a new release. I'd also be interested in your comments on the data structures. I think the choice of data frame was probably wrong for the comorbidities: it should be a matrix with named rows, since all the values are of logical type. This certainly works better on the C++ side. What do you think?

**Comment by wmurphyrd** [comment]
Matrix is the best match for the form of the data, but 90% of the time I'm going to want the comorbidities merged back into my main data frame for the study data in order to use them in regression or pass the data set onto the statistician. That's easy enough to accomplish with merge by row.names if the data is in a matrix with names, so the impact on usability would be neutral. 

So, I'd say go for it if the back end benefit outweighs the effort to implement it, but there's nothing wrong with receiving the results as a data frame from the user perspective.

**Comment by jackwasey** [comment]
I just merged a lot of new code into the master branch including your t(t( fix and your test cases. The fix for the other issue turned out to be a little different to your solution. Thanks for the input. Now would be a good time for us to add other scoring systems, as you suggest, now the base code is looking good.

**Comment by wmurphyrd** [comment]
This is great timing as I'm finalizing the data processing for this study and now I'll be able to cite your package directly rather than your package + an appendix with modifications. Do you have a cran release planned in the immediate future? I can just cite the specific github commit I'm using if not. 

I had a question for you on the way you match codes to the comorbidity definitions. I ended up having to implement Quan's ICD10 mappings for Charlson and Elixhauser in order to pool my US and Australian data, and I noticed that Quan's published SAS code often contains partial codes (e.g. a group of codes listed as "I21.x" in the paper becomes just "I21" in the SAS code), so I had to use partial matching in the implementation. 

Did you find the same issue with the ICD9 comorbditiy definitions and also use partial matching? (I don't know cpp well enough to check for myself in the source). Thanks.

I'll also be working on updating my vanWalraven score implementation to match the latest changes and send in a pull request

**Comment by jackwasey** [comment]
Excellent. I just submitted a CRAN update, but had to make some minimal changes, so resubmitting imminently after testing.

The current comorbidity assignment is done by converting everything to factors (ensuring that the mappings have the same levels as the source data), then matching on the underlying integers, which is very fast. For you, this just means that it will exact match everything in the mapping you provide. The solution I used for including all possible (even fictional) child codes was to list them all out explicitly. You can use `icd9GetReal` to find just the real (ICD-9, not ICD-10 yet). Internally, I use icd9ExpandMinor to filll out all possible codes after the decimal place, which may be useful to you.

When Quan used a range of ICD-9 codes, I used the %i9s% and sibling functions to expand out all the possible codes in between.

In fact, the comorbidity matching doesn't bother checking against the entire map, or what is 'real' or valid: it drops all the mapping codes which don't appear in the data to be tested, which makes it much faster.

Your Van Walvaran patch would be very welcome, as would anything you've done with ICD-10 codes, which I've not needed to look at yet. I am hoping there will be a lot of common ground with ICD-9, and they should be a bit simpler since the codes some to be structures more consistently.

I'm not exactly sure of the official way of citing my package, but, however you do it, this is much appreciated.

**Comment by wmurphyrd** [comment]
That is a very clever way to go about it. I'm about to send a pull request for the van Walraven methods. I can also share what I did with ICD10, but it was "get this analysis completed" type of work and not "create a shareable package" work. I'll put it as a branch on my fork and send you a link

**Comment by wmurphyrd** [comment]
Forgot to mention: that CRAN release was perfectly timed. I finished my data processing with the icd9 1.1 release and sent it off the the statistician. I'll send you a copy of the paper when it's out

**Pull request closed without merging**
